- name: install apache2 
  remote_user: azureuser2
  hosts: 4.180.28.82
  become: true 
  become_user: root 
  gather_facts: true 
  tasks: 
    - name: "Install apache2" 
    package: 
      name=apache2 
      state=present
